from __future__ import annotations

from typing import Any

CATEGORY_META = [
    {
        "slug": "grill",
        "title": "Шашлык",
        "subtitle": "Мясо на углях, люля и быстрые горячие закуски.",
        "note": "К блюдам подаётся лаваш и овощной салат — бесплатно",
        "colors": ("#4C2A1B", "#A65D35"),
    },
    {
        "slug": "first_courses",
        "title": "Первые блюда",
        "subtitle": "Супы и наваристые блюда для плотного обеда.",
        "colors": ("#6A4A2C", "#C38A44"),
    },
    {
        "slug": "second_courses",
        "title": "Вторые блюда",
        "subtitle": "Основные блюда кухни кафе для самовывоза.",
        "colors": ("#31473A", "#65806A"),
    },
    {
        "slug": "samsa",
        "title": "Самса",
        "subtitle": "Печёная самса разных видов из теста и мяса.",
        "colors": ("#6F3C2C", "#C5714F"),
    },
    {
        "slug": "salads",
        "title": "Салаты",
        "subtitle": "Классические салаты и холодные закуски.",
        "colors": ("#355C4A", "#77A089"),
    },
    {
        "slug": "drinks",
        "title": "Напитки",
        "subtitle": "Компоты и чай из основного меню.",
        "colors": ("#305A6D", "#5F9CB8"),
    },
    {
        "slug": "coffee_tea",
        "title": "Кофе и чай",
        "subtitle": "Кофейная карта и фирменные горячие напитки.",
        "colors": ("#493628", "#B08968"),
    },
]
CATEGORY_BY_SLUG = {entry["slug"]: entry for entry in CATEGORY_META}
CATEGORY_ORDER = {entry["slug"]: index for index, entry in enumerate(CATEGORY_META)}

MENU_SEED: list[dict[str, Any]] = [
    {
        "id": 1,
        "category": "grill",
        "name": "Шашлык из говядины",
        "description": "Порция 200 г. Подаётся как горячее блюдо для самовывоза.",
        "price": 600,
        "sort_order": 1,
    },
    {
        "id": 2,
        "category": "grill",
        "name": "Шашлык из баранины",
        "description": "Порция 200 г. Насыщенный вкус и плотная мясная подача.",
        "price": 600,
        "sort_order": 2,
    },
    {
        "id": 3,
        "category": "grill",
        "name": "Люля-кебаб",
        "description": "Порция 200 г. Классический люля для быстрого заказа.",
        "price": 600,
        "sort_order": 3,
    },
    {
        "id": 4,
        "category": "grill",
        "name": "Шашлык из печени бараньей",
        "description": "Порция 200 г. Горячая мясная позиция из меню кафе.",
        "price": 550,
        "sort_order": 4,
    },
    {
        "id": 5,
        "category": "grill",
        "name": "Шашлык из куриных крылышек",
        "description": "Порция 300 г. Подходит для компании или плотного перекуса.",
        "price": 600,
        "sort_order": 5,
    },
    {
        "id": 6,
        "category": "grill",
        "name": "Шашлык из куриной грудки",
        "description": "Порция 200 г. Более лёгкий вариант шашлыка.",
        "price": 600,
        "sort_order": 6,
    },
    {
        "id": 7,
        "category": "grill",
        "name": "Ролл-шашлык",
        "description": "Порция 400 г. Удобная позиция для быстрого заказа навынос.",
        "price": 300,
        "sort_order": 7,
    },
    {
        "id": 8,
        "category": "grill",
        "name": "Картофель фри",
        "description": "Порция 100 г. Хорошо дополняет мясные блюда.",
        "price": 150,
        "sort_order": 8,
    },
    {
        "id": 9,
        "category": "first_courses",
        "name": "Шурпа",
        "description": "Горячее первое блюдо для сытного обеда.",
        "price": 400,
        "sort_order": 1,
    },
    {
        "id": 10,
        "category": "first_courses",
        "name": "Мастава",
        "description": "Домашний суп из основного меню кафе.",
        "price": 400,
        "sort_order": 2,
    },
    {
        "id": 11,
        "category": "first_courses",
        "name": "Суп из чечевицы",
        "description": "Лёгкий суп на каждый день.",
        "price": 230,
        "sort_order": 3,
    },
    {
        "id": 12,
        "category": "first_courses",
        "name": "Борщ",
        "description": "Классический горячий борщ из меню кафе.",
        "price": 300,
        "sort_order": 4,
    },
    {
        "id": 13,
        "category": "first_courses",
        "name": "Мясо по-казахски",
        "description": "Сытное блюдо, размещённое в разделе первых блюд.",
        "price": 350,
        "sort_order": 5,
    },
    {
        "id": 14,
        "category": "first_courses",
        "name": "Лагман",
        "description": "Горячий лагман для полноценного обеда.",
        "price": 380,
        "sort_order": 6,
    },
    {
        "id": 15,
        "category": "second_courses",
        "name": "Микс (плов и шашлык)",
        "description": "Комбинация двух популярных позиций в одном заказе.",
        "price": 650,
        "sort_order": 1,
    },
    {
        "id": 16,
        "category": "second_courses",
        "name": "Плов",
        "description": "Основное блюдо с рисом и мясом.",
        "price": 350,
        "sort_order": 2,
    },
    {
        "id": 17,
        "category": "second_courses",
        "name": "Манты",
        "description": "Порция 5 шт. Горячее блюдо для заказа навынос.",
        "price": 350,
        "sort_order": 3,
    },
    {
        "id": 18,
        "category": "second_courses",
        "name": "Жаровня",
        "description": "Мясо и овощи, порция 250 г.",
        "price": 600,
        "sort_order": 4,
    },
    {
        "id": 19,
        "category": "second_courses",
        "name": "Мясо по-французски",
        "description": "Горячее основное блюдо для сытного заказа.",
        "price": 600,
        "sort_order": 5,
    },
    {
        "id": 42,
        "category": "second_courses",
        "name": "Лепёшка 100 г",
        "description": "Свежая лепёшка, большая порция.",
        "price": 100,
        "sort_order": 6,
    },
    {
        "id": 43,
        "category": "second_courses",
        "name": "Лепёшка 50 г",
        "description": "Свежая лепёшка, средняя порция.",
        "price": 50,
        "sort_order": 7,
    },
    {
        "id": 44,
        "category": "second_courses",
        "name": "Лепёшка 25 г",
        "description": "Свежая лепёшка, малая порция.",
        "price": 25,
        "sort_order": 8,
    },
    {
        "id": 20,
        "category": "samsa",
        "name": "Самса из курицы",
        "description": "Порция 200 г. Тёплая выпечка для быстрого перекуса.",
        "price": 150,
        "sort_order": 1,
    },
    {
        "id": 21,
        "category": "samsa",
        "name": "Самса из баранины",
        "description": "Порция 185 г. Более насыщенный мясной вариант.",
        "price": 200,
        "sort_order": 2,
    },
    {
        "id": 22,
        "category": "samsa",
        "name": "Самса из говядины",
        "description": "Порция 185 г. Классическая мясная самса.",
        "price": 150,
        "sort_order": 3,
    },
    {
        "id": 23,
        "category": "samsa",
        "name": "Самса из говядины с картофелем",
        "description": "Порция 185 г. Более мягкий вкус за счёт картофеля.",
        "price": 140,
        "sort_order": 4,
    },
    {
        "id": 24,
        "category": "samsa",
        "name": "Мини-самса с говядиной",
        "description": "Порция 4 шт. Удобный формат для компании.",
        "price": 180,
        "sort_order": 5,
    },
    {
        "id": 25,
        "category": "salads",
        "name": "Ассорти из солёных овощей",
        "description": "Холодная закуска к горячим блюдам.",
        "price": 200,
        "sort_order": 1,
    },
    {
        "id": 26,
        "category": "salads",
        "name": "Салат овощной",
        "description": "Свежий овощной салат из повседневного меню.",
        "price": 200,
        "sort_order": 2,
    },
    {
        "id": 27,
        "category": "salads",
        "name": "Салат Оливье",
        "description": "Классическая салатная позиция.",
        "price": 200,
        "sort_order": 3,
    },
    {
        "id": 28,
        "category": "salads",
        "name": "Язык салат",
        "description": "Более сытный салат из холодных блюд.",
        "price": 280,
        "sort_order": 4,
    },
    {
        "id": 29,
        "category": "drinks",
        "name": "Компот",
        "description": "300 мл. Лёгкий напиток к основному заказу.",
        "price": 50,
        "sort_order": 1,
    },
    {
        "id": 30,
        "category": "drinks",
        "name": "Компот сливовый",
        "description": "300 мл. Более насыщенный вкус компота.",
        "price": 70,
        "sort_order": 2,
    },
    {
        "id": 31,
        "category": "drinks",
        "name": "Чай чайник",
        "description": "Чайник на компанию.",
        "price": 200,
        "sort_order": 3,
    },
    {
        "id": 32,
        "category": "drinks",
        "name": "Чай с лимоном",
        "description": "200 мл. Быстрый горячий напиток.",
        "price": 25,
        "sort_order": 4,
    },
    {
        "id": 33,
        "category": "coffee_tea",
        "name": "Американо",
        "description": "200 мл. Базовый кофе из меню напитков.",
        "price": 150,
        "sort_order": 1,
    },
    {
        "id": 34,
        "category": "coffee_tea",
        "name": "Горячий шоколад",
        "description": "300 мл. Плотный сладкий горячий напиток.",
        "price": 200,
        "sort_order": 2,
    },
    {
        "id": 35,
        "category": "coffee_tea",
        "name": "Капучино 300 мл",
        "description": "Большой стакан капучино.",
        "price": 230,
        "sort_order": 3,
    },
    {
        "id": 36,
        "category": "coffee_tea",
        "name": "Капучино 200 мл",
        "description": "Стандартная порция капучино.",
        "price": 180,
        "sort_order": 4,
    },
    {
        "id": 37,
        "category": "coffee_tea",
        "name": "Латте",
        "description": "300 мл. Мягкий молочный кофе.",
        "price": 220,
        "sort_order": 5,
    },
    {
        "id": 38,
        "category": "coffee_tea",
        "name": "Раф",
        "description": "300 мл. Более сливочный кофейный напиток.",
        "price": 250,
        "sort_order": 6,
    },
    {
        "id": 39,
        "category": "coffee_tea",
        "name": "Флэт уайт",
        "description": "200 мл. Крепкий кофейный напиток с молоком.",
        "price": 220,
        "sort_order": 7,
    },
    {
        "id": 40,
        "category": "coffee_tea",
        "name": "Чай восточный",
        "description": "500 мл. Чайник фирменного чая.",
        "price": 300,
        "sort_order": 8,
    },
    {
        "id": 41,
        "category": "coffee_tea",
        "name": "Чай сибирский",
        "description": "500 мл. Чайник авторского чая.",
        "price": 300,
        "sort_order": 9,
    },
]

VARIANT_GROUPS: dict[str, dict[str, Any]] = {
    "lepeshka": {
        "name": "Лепёшка",
        "description": "Свежая лепёшка. Выберите размер.",
        "item_ids": [42, 43, 44],
        "labels": {42: "100 г", 43: "50 г", 44: "25 г"},
    },
}
ITEM_TO_VARIANT_GROUP: dict[int, str] = {}
for _group_key, _group_data in VARIANT_GROUPS.items():
    for _item_id in _group_data["item_ids"]:
        ITEM_TO_VARIANT_GROUP[_item_id] = _group_key
